In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix, classification_report

In [ ]:
data = pd.read_csv('polymerase_cluster-BI.csv')
data.head()

index                                                ABS         0  \
0     1  abstract astrocytes produce granulocytemacroph... -0.050448   
1     2  abstract replication of avian infectious bronc... -0.128422   
2     3  abstract the infectivity of vesicular stomatit... -0.095019   
3     4  abstract two temporally and enzymatically dist... -0.134657   
4     5  abstract rnadependent rna polymerase rdrp acti... -0.222713   

          1         2         3         4         5         6         7  ...  \
0  0.017385 -0.039777 -0.067159 -0.029633  0.074573 -0.050444 -0.010799  ...   
1 -0.084803  0.084813 -0.013748  0.006486  0.128668  0.032655  0.066775  ...   
2 -0.032279  0.017571 -0.065860  0.001315  0.048199 -0.031072  0.010103  ...   
3 -0.086097  0.026415 -0.027553 -0.020280 -0.044637 -0.013312 -0.033345  ...   
4 -0.100353  0.107456 -0.079828  0.030818 -0.091040 -0.014809  0.012756  ...   

   G1  G2  G3  G4  G5  G6  G7  G8  G9  G10  
0   0   0   0   0   0   1   0   0   0  0.0  
1   0   0   0   0   0   1   0   0   0  0.0  
2   0   0   0   0   0   1   0   0   0  0.0  
3   0   0   0   0   0   0   1   0   0  0.0  
4   0   0   0   0   0   0   1   0   0  0.0  

[5 rows x 42 columns]

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2782 entries, 0 to 2782
Data columns (total 42 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   index   2782 non-null   object 
 1   ABS     2782 non-null   object 
 2   0       2782 non-null   float64
 3   1       2782 non-null   float64
 4   2       2782 non-null   float64
 5   3       2782 non-null   float64
 6   4       2782 non-null   float64
 7   5       2782 non-null   float64
 8   6       2782 non-null   float64
 9   7       2782 non-null   float64
 10  8       2782 non-null   float64
 11  9       2782 non-null   float64
 12  10      2782 non-null   float64
 13  11      2782 non-null   float64
 14  12      2782 non-null   float64
 15  13      2782 non-null   float64
 16  14      2782 non-null   float64
 17  15      2782 non-null   float64
 18  16      2782 non-null   float64
 19  17      2782 non-null   float64
 20  18      2782 non-null   float64
 21  19      2782 non-null   float64
 22  20   

In [ ]:
data.describe()

0            1            2            3            4  \
count  2782.000000  2782.000000  2782.000000  2782.000000  2782.000000   
mean     -0.006256    -0.006805     0.000002    -0.001416    -0.000034   
std       0.135629     0.095939     0.082939     0.082707     0.079708   
min      -0.284363    -0.210271    -0.259660    -0.199337    -0.202987   
25%      -0.113374    -0.073097    -0.055179    -0.060157    -0.047112   
50%      -0.024205    -0.026229     0.001556    -0.015129    -0.012831   
75%       0.092567     0.038582     0.055740     0.044334     0.033604   
max       0.389576     0.343473     0.269622     0.307179     0.402218   

                 5            6            7            8            9  ...  \
count  2782.000000  2782.000000  2782.000000  2782.000000  2782.000000  ...   
mean     -0.002247     0.000039     0.000487    -0.001165     0.000761  ...   
std       0.077969     0.073826     0.068710     0.066997     0.068602  ...   
min      -0.237105    -0.255140    -0.355713    -0.213472    -0.230506  ...   
25%      -0.055859    -0.047340    -0.029521    -0.041757    -0.039536  ...   
50%      -0.007865    -0.008074    -0.000190    -0.004953     0.000924  ...   
75%       0.044956     0.041129     0.029913     0.032115     0.040680  ...   
max       0.358950     0.319398     0.416263     0.437870     0.266771  ...   

                G1           G2           G3           G4           G5  \
count  2782.000000  2782.000000  2782.000000  2782.000000  2782.000000   
mean      0.017254     0.120776     0.133357     0.089863     0.132998   
std       0.130239     0.325926     0.340022     0.286037     0.339633   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

                G6           G7           G8           G9          G10  
count  2782.000000  2782.000000  2782.000000  2782.000000  2782.000000  
mean      0.229331     0.112868     0.023364     0.118260     0.021927  
std       0.420478     0.316489     0.151085     0.322974     0.146470  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 40 columns]

In [ ]:
data.isna().sum()

index    0
ABS      0
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
G1       0
G2       0
G3       0
G4       0
G5       0
G6       0
G7       0
G8       0
G9       0
G10      0
dtype: int64

In [ ]:
data.columns

Index(['index', 'ABS', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', 'G1', 'G2', 'G3', 'G4', 'G5',
       'G6', 'G7', 'G8', 'G9', 'G10'],
      dtype='object')

In [ ]:
X = data[['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29']]
y = data[['G1','G2','G3','G4','G5','G6','G7','G8','G9']]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
acc = accuracy_score(y_test,y_pred)
print('Accuracy:',acc*100,'%')

Accuracy: 92.63913824057451 %


In [ ]:
cr = classification_report(y_test,y_pred)
print('Classification Report:',cr)

Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.96      0.98        68
           2       1.00      0.94      0.97        77
           3       1.00      0.93      0.97        45
           4       0.97      0.96      0.96        67
           5       0.99      0.96      0.98       132
           6       1.00      0.96      0.98        73
           7       1.00      0.88      0.93        16
           8       1.00      0.73      0.85        64

   micro avg       0.99      0.93      0.96       550
   macro avg       1.00      0.92      0.96       550
weighted avg       0.99      0.93      0.96       550
 samples avg       0.91      0.91      0.91       550



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
conf_matrix = multilabel_confusion_matrix(y_test,y_pred)
print('Confusion Matrix:',conf_matrix)

Confusion Matrix: [[[549   0]
  [  0   8]]

 [[489   0]
  [  3  65]]

 [[480   0]
  [  5  72]]

 [[512   0]
  [  3  42]]

 [[488   2]
  [  3  64]]

 [[424   1]
  [  5 127]]

 [[484   0]
  [  3  70]]

 [[541   0]
  [  2  14]]

 [[493   0]
  [ 17  47]]]
